[tools]
python = "3.12" # [optional] will be used for the venv

[env]
_.python.venv = { path = ".venv", create = true } # create the venv if it doesn't exist
_.file = ".env"
AWS_ACCESS_KEY_ID="localstack"
AWS_SECRET_ACCESS_KEY="localstack"
AWS_DEFAULT_REGION="us-east-1"
AWS_ENDPOINT_URL="http://localhost:4566"
